apiVersion: v1
kind: Service
metadata:
  name: loco-assessment
  labels:
    app: loco-assessment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: loco-assessment
  type: LoadBalancer
